name: scan_23
description: "Flutter document scanner and image processing app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  font_awesome_flutter: ^10.8.0
  flutter_localizations:
      sdk: flutter
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.15
  get: 4.6.6
  intl: ^0.19.0
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  flutter_doc_scanner: ^0.0.12
  saver_gallery: ^4.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  analyzer: ^6.5.0

flutter:
  generate : true
  uses-material-design: true

  assets:
  - assets/

  fonts:
   - family: Roboto
     fonts:
      - asset: fonts/Roboto-Thin.ttf
        weight: 200
      - asset: fonts/Roboto-Light.ttf
        weight: 200
      - asset: fonts/Roboto-Regular.ttf
        weight: 200
      - asset: fonts/Roboto-Medium.ttf
        weight: 300
      - asset: fonts/Roboto-Bold.ttf
        weight: 600

